version: 1.0.{build}
configuration: Release
platform: Any CPU
before_build:
- cmd: nuget restore
build:
  parallel: true
  verbosity: minimal
after_build:
- cmd: nuget pack modules\Innofactor.Xrm.Utils.Common\Innofactor.Xrm.Utils.Common.csproj -Properties Configuration=Release;Platform=AnyCPU -Version %APPVEYOR_BUILD_VERSION%
- cmd: nuget pack modules\Innofactor.Xrm.Utils.Common\Innofactor.Xrm.Utils.Plugin.csproj -Properties Configuration=Release;Platform=AnyCPU -Version %APPVEYOR_BUILD_VERSION%
- cmd: nuget pack modules\Innofactor.Xrm.Utils.Common\Innofactor.Xrm.Utils.Workflow.csproj -Properties Configuration=Release;Platform=AnyCPU -Version %APPVEYOR_BUILD_VERSION%
artifacts:
- path: '*.nupkg'