version: 1.0.{build}
image:
  - Visual Studio 2017
configuration: Release
platform: Any CPU
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
- cmd: nuget restore
build:
  parallel: true
  verbosity: minimal
after_build:
- cmd: nuget pack modules\Innofactor.Xrm.Utils.Common\Innofactor.Xrm.Utils.Common.csproj -Properties Configuration=Release;Platform=AnyCPU -Version %APPVEYOR_BUILD_VERSION%
- cmd: nuget pack modules\Innofactor.Xrm.Utils.Plugin\Innofactor.Xrm.Utils.Plugin.csproj -Properties Configuration=Release;Platform=AnyCPU -Version %APPVEYOR_BUILD_VERSION%
- cmd: nuget pack modules\Innofactor.Xrm.Utils.Workflow\Innofactor.Xrm.Utils.Workflow.csproj -Properties Configuration=Release;Platform=AnyCPU -Version %APPVEYOR_BUILD_VERSION%
artifacts:
- path: '*.nupkg'